CREATE TABLE Customer(
	CustID VARCHAR(6) NOT NULL,
	CustTitle VARCHAR(5),
	CustName VARCHAR(30) NOT NULL,
	DOB DATE,
	salary decimal(10,2) not null,
	CustAddress VARCHAR(30),
	City VARCHAR(20),
	Province VARCHAR(20),
	PostalCode VARCHAR(9),
	CONSTRAINT PRIMARY KEY (CustID)
);
CREATE TABLE Orders(
	OrderID VARCHAR(6) NOT NULL,
	OrderDate DATE,
	CustID VARCHAR(6) NOT NULL,
	CONSTRAINT PRIMARY KEY (OrderID),
	CONSTRAINT FOREIGN KEY(CustID) REFERENCES Customer(CustID)
	ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE Item(
	ItemCode VARCHAR(6) NOT NULL,
	Description VARCHAR(50) NOT NULL,
	PackSize VARCHAR(20),
	UnitPrice DECIMAL(6,2) NOT NULL,
	QtyOnHand INT(5) NOT NULL,
	CONSTRAINT PRIMARY KEY (ItemCode)
);
CREATE TABLE OrderDetail(
	OrderID VARCHAR(6) NOT NULL,
	ItemCode VARCHAR(6) NOT NULL,
	OrderQTY INT(11) NOT NULL,
	Discount INT(2),
	CONSTRAINT PRIMARY KEY (OrderID,ItemCode),
	CONSTRAINT FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ItemCode) REFERENCES Item(ItemCode)
	ON UPDATE CASCADE ON DELETE CASCADE
);

